version: '3'
services:
  bbd:
    container_name: battlebit-docker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/home/steam/config
      # Uncomment this line to use the dir ./game with the game files
      # inside and uncomment the steam install line inside the run.sh
      # - ./game:/home/steam/battlebit
    env_file:
      - config/.env
